// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmFTUVS4TASKsv6BzEvUyHiWkObzaMZNU',
    appId: '1:582788106589:web:69502e4e43fa30e4a040b4',
    messagingSenderId: '582788106589',
    projectId: 'aunthentication-59bd3',
    authDomain: 'aunthentication-59bd3.firebaseapp.com',
    storageBucket: 'aunthentication-59bd3.appspot.com',
    measurementId: 'G-K9TCNGNR41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByIBZgwYvuVwhZFRg8HJNpUvi4-EcsgQw',
    appId: '1:582788106589:android:e70d5c250b7605b0a040b4',
    messagingSenderId: '582788106589',
    projectId: 'aunthentication-59bd3',
    storageBucket: 'aunthentication-59bd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCobFtXF-extSmeAOLeQA5QNDhmJdubo-k',
    appId: '1:582788106589:ios:35d2e6544fa2867fa040b4',
    messagingSenderId: '582788106589',
    projectId: 'aunthentication-59bd3',
    storageBucket: 'aunthentication-59bd3.appspot.com',
    iosBundleId: 'com.example.aunthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCobFtXF-extSmeAOLeQA5QNDhmJdubo-k',
    appId: '1:582788106589:ios:35d2e6544fa2867fa040b4',
    messagingSenderId: '582788106589',
    projectId: 'aunthentication-59bd3',
    storageBucket: 'aunthentication-59bd3.appspot.com',
    iosBundleId: 'com.example.aunthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmFTUVS4TASKsv6BzEvUyHiWkObzaMZNU',
    appId: '1:582788106589:web:1f7cef257f3ce5c8a040b4',
    messagingSenderId: '582788106589',
    projectId: 'aunthentication-59bd3',
    authDomain: 'aunthentication-59bd3.firebaseapp.com',
    storageBucket: 'aunthentication-59bd3.appspot.com',
    measurementId: 'G-55PT3XH51E',
  );
}
